### ISSUE TITLE
PAPER

### ISSUE THREAD

**Issue by Penny8336** [jiayiwang5/Chinese-ChatBot#10]
你好..有看到註解...# equation (6) of the paper
想請問參考哪一篇paper呢

**Comment by Penny8336** [comment]
你好 想問多問一些問題，
因為我想將模型學習的hidden state做視覺化分析，了解input 對hidden state的關係
有幾個問題想請教
1. question_h, question_c是encoder lstm 總結出的hidden state??
2. prediction_h, prediction_c是decoder lstm 的hidden state??
3. 關於裡面attention的作法不是很清楚

因為在我了解attention 是將encoder 個別hidden state乘上權重
給每個時間步長使用，所以希望能了解此篇做法..是參考哪篇paper 謝謝!!

我所理解的attention: https://jalammar.github.io/visualizing-neural-machine-translation-mechanics-of-seq2seq-models-with-attention/

謝謝您的幫助及先前的回答~希望可以撥空解答謝謝!!!

**Comment by jayeew** [comment]
> 你好 想問多問一些問題，
> 因為我想將模型學習的hidden state做視覺化分析，了解input 對hidden state的關係
> 有幾個問題想請教
> 1. question_h, question_c是encoder lstm 總結出的hidden state??
> 2. prediction_h, prediction_c是decoder lstm 的hidden state??
> 3. 關於裡面attention的作法不是很清楚
> 
> 因為在我了解attention 是將encoder 個別hidden state乘上權重
> 給每個時間步長使用，所以希望能了解此篇做法..是參考哪篇paper 謝謝!!
> 
> 我所理解的attention: https://jalammar.github.io/visualizing-neural-machine-translation-mechanics-of-seq2seq-models-with-attention/
> 
> 謝謝您的幫助及先前的回答~希望可以撥空解答謝謝!!!

手头没电脑，用手机简短说几句吧，见谅。_h是hidden state，_c是cell state，两者是lstm单元的输出。留下你的邮箱，我把论文和一张attention结构图发给你，结合图 论文 和我的代码三者看，你会很快理解。

**Comment by Penny8336** [comment]
謝謝 真是麻煩你了, 以下是我的信箱
60847071s@gapps.ntnu.edu.tw
感謝你的熱心

**Comment by jayeew** [comment]
> 謝謝 真是麻煩你了, 以下是我的信箱
> [60847071s@gapps.ntnu.edu.tw](mailto:60847071s@gapps.ntnu.edu.tw)
> 感謝你的熱心

很道歉没能及时回复你，通知邮件被qq屏蔽了，昨晚十一点多了我看了眼你不在就先睡下了。论文和图已经发给你了。
