### ISSUE TITLE
beam search 结果超出词表索引

### ISSUE THREAD

**Issue by ZJY382653** [jiayiwang5/Chinese-ChatBot#12]
您好，最近在跑您训练好的模型时，发现用beam search 搜索时，结果会超出词表索引范围，想请问下您是否遇到过类似情况。
![snipaste_20200703_155554](https://user-images.githubusercontent.com/49870267/86446066-02c44900-bd46-11ea-83ed-84f45ef75f60.png)
![snipaste_20200703_155611](https://user-images.githubusercontent.com/49870267/86446099-0ce64780-bd46-11ea-8fa3-14b396c5ce2e.png)

还想请问您，如果自己训练模型，大概需要训练几个epoch

**Comment by jayeew** [comment]
beamsearch整体算法有问题我一直没解决，你可以放弃我写的去参考下别人的。
epoch具体我忘了，在代码里不是提供了一个现成的模型吗，那个weight名字就是按epoch序号递增的，没记错的的话是185吧。
词表超出范围你在贪婪方法里有遇到吗?如果也有遇到，就是你运行getdata生成的表和我之前训练模型时候生成的表不一致，所以你可以删掉模型自己训练或别运行getdata直接加载模型。这个问题前面有人问过，你可以翻翻关闭的话题。



---原始邮件---
发件人: "ZJY382653"<notifications@github.com&gt;
发送时间: 2020年7月3日(周五) 下午3:59
收件人: "jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [jiayiwang5/Chinese-ChatBot] beam search 结果超出词表索引 (#12)




 
您好，最近在跑您训练好的模型时，发现用beam search 搜索时，结果会超出词表索引范围，想请问下您是否遇到过类似情况。
 
 
 
还想请问您，如果自己训练模型，大概需要训练几个epoch

**Comment by ZJY382653** [comment]
词表超出范围这个问题在贪婪方法里没有遇到，能够正常运行。现有的模型是184。
谢谢您的回复！！！我自己再找找解决方法。
