### ISSUE TITLE
这个可以直接训练英文语料么？

### ISSUE THREAD

**Issue by albertyou2** [jiayiwang5/Chinese-ChatBot#13]
你好这个库可以直接训练英文预料么？需要怎么修改呢

**Comment by jayeew** [comment]
道歉来晚了，您是指纯英文对话吗?是的话，实践起来是要比中文对话简单些的。下面我分几点来讲。
- 数据预处理时候英语单词直接按空格切分，不用中文那样分词，词典会更简洁。
- 数据丢进模型时,word embedding可以训练好的英文权重，这个你可在网上找到，效果更好，中文的话我找不到训练好的只能初试化一个随机的。
- 模型重新训练，整体结构可以保留，当然如果你有更好的结构可以随意修改。

**Comment by albertyou2** [comment]
不好意思这几天公司很忙，今天才有时间看，谢谢回答
