### ISSUE TITLE
项目问题

### ISSUE THREAD

**Issue by jpyjpr** [jiayiwang5/Chinese-ChatBot#15]
你好，没有main.py和START.bat文件呀！！

**Comment by jayeew** [comment]
> 你好，没有main.py和START.bat文件呀！！

额，52来的吧，main就是把预测文件改了个名而已，bat是装环境，你自己跑缺啥装啥就行

**Comment by jpyjpr** [comment]
噢噢 好嘞 谢谢!!

**Comment by jpyjpr** [comment]
那请问我该运行哪个文件呀？只有langconv.py,zh_wiki.还有_init_.py这三个python文件
