### ISSUE TITLE
不加attention机制的model

### ISSUE THREAD

**Issue by Zhouziyi828** [jiayiwang5/Chinese-ChatBot#18]
请问能提供一下不带attention机制的model嘛，用来做对比实验！谢谢！

**Comment by jayeew** [comment]
> 请问能提供一下不带attention机制的model嘛，用来做对比实验！谢谢！

注意文件列表里的non-attention文件

**Comment by Zhouziyi828** [comment]
> 
这个non-attention.ipynb的文件加载的是models/W--157-0.6163-.h5这个诶，这个是不带attention机制的吧？但是这个文件不存在

**Comment by jayeew** [comment]
> > 
> 
> 这个non-attention.ipynb的文件加载的是models/W--157-0.6163-.h5这个诶，这个是不带attention机制的吧？但是这个文件不存在

那应该是无注意力的模型我没传，你只能重新训练了

**Comment by Zhouziyi828** [comment]
> > > 
> > 
> > 
> > 这个non-attention.ipynb的文件加载的是models/W--157-0.6163-.h5这个诶，这个是不带attention机制的吧？但是这个文件不存在
> 
> 那应该是无注意力的模型我没传，你只能重新训练了

哈哈好的，已经在练了，只是需要的时间有点长所以来问问！谢谢！
