### ISSUE TITLE
very good

### ISSUE THREAD

**Issue by Rokafavour** [jiayiwang5/Chinese-ChatBot#19]
赞一个，有些作者留个代码也不调试就不管了，一堆报错最后还不能正常对话。有这么简便的程序爱了

**Comment by jayeew** [comment]
多谢支持，这是我本科阶段初步接触深度学习时的小试牛刀，开源放出来希望给更多两眼抓瞎的初学者一点帮助。虽然已经不做NLP了，但这个project下的所有issues我都会尽力帮助解决。
