### ISSUE TITLE
from keras.layers.attention import AttentionLayer

### ISSUE THREAD

**Issue by pochenglin66** [jiayiwang5/Chinese-ChatBot#2]
--> from keras.layers.attention import AttentionLayer
ModuleNotFoundError: No module named 'keras.layers.attention'

Can you provide requirement.txt of this project?
thanks!

**Comment by vcbeaut** [comment]
delete it is okay

**Comment by jayeew** [comment]
sorry , I havn't sign in for a long time.Actually I have forgot some details.It seems that layers.attention is just a failure instance that I havn't remove.
