### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by KrisTHL181** [jiayiwang5/Chinese-ChatBot#21]
Traceback (most recent call last):
  File "chatbot_inference_Attention.ipynb", line 372, in <module>
    "scrolled": true
NameError: name 'true' is not defined

**Comment by jayeew** [comment]
截图看一下，我这定位不到你的报错情况。
虽然没定位你的错误，但是有两种可能的解决方案请你参考。

1. 'true'改成'True'；
2. [参考这里](https://stackoverflow.com/questions/56427716/unable-to-import-numpy-in-jupyter-instead-getting-nameerror-true-is-not-def)
