### ISSUE TITLE
对新版库不兼容情况

### ISSUE THREAD

**Issue by anfogy** [jiayiwang5/Chinese-ChatBot#22]
虽然自己修修能搞定，但还是希望可以给新手一点小帮助，然后是在chatbot_train.ipynb里面有modles的错误拼写

**Comment by jayeew** [comment]
确实间隔时间太长了，难免api变动，可以参考主要思路自己尝试重构一下

**Comment by anfogy** [comment]
> 确实间隔时间太长了，难免api变动，可以参考主要思路自己尝试重构一下

不介意的话可以pr一个我修过的版本吗？

**Comment by jayeew** [comment]
> > 确实间隔时间太长了，难免api变动，可以参考主要思路自己尝试重构一下
> 
> 不介意的话可以pr一个我修过的版本吗？

不好意思 最近改论文没啥时间，建议多熟悉一下pytorch或keras，在草稿纸上算好维度变化过程，参考我的老代码逻辑试着重写一下
