### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (105575,) + inhomogeneous part.

### ISSUE THREAD

**Issue by zige** [jiayiwang5/Chinese-ChatBot#23]
line 122, in <module>
    answer_a = np.array([[word_to_index[w] for w in i.split(' ')] for i in answer_a])

**Comment by jayeew** [comment]
建议参考一下这里

[ValueError: setting an array element with a sequence.](https://stackoverflow.com/questions/4674473/valueerror-setting-an-array-element-with-a-sequence)
