### ISSUE TITLE
作者数据处理之后把索引全加一了，有什么作用吗？

### ISSUE THREAD

**Issue by vcbeaut** [jiayiwang5/Chinese-ChatBot#3]
for i, j in word_to_index.items():
    word_to_index[i] = j + 1

index_to_word = {}
for key, value in word_to_index.items():
    index_to_word[value] = key
pad_question = question
pad_answer_a = answer_a
pad_answer_b = answer_b

for pos, i in enumerate(pad_question):
    for pos_, j in enumerate(i):
        i[pos_] = j + 1
    if(len(i) > answer_maxLen):
        pad_question[pos] = i[:answer_maxLen]

**Comment by jayeew** [comment]
你还在吗lol
开始编号的时候是从0开始的，这没有什么问题，但是后面有一个padding的补全操作，这是因为encoder的输入要求长度统一，既长的截取，短的补全，那么用0来补全是最简洁不过了，所以我把0腾了出来。
