### ISSUE TITLE
train by self

### ISSUE THREAD

**Issue by Penny8336** [jiayiwang5/Chinese-ChatBot#4]
你好，順利跑完成你的code
我想用自己找到的語料庫去訓練資料同樣10萬筆，get_data前製作業處理好了，
但是train的時候一直報錯，可以請問一下是為什麼嘛?

AlreadyExistsError: Resource __per_step_3/RMSprop/gradients/decoder_lstm/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node RMSprop/gradients/decoder_lstm/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]

**Comment by Penny8336** [comment]
可以分享一下tensorflow keras的版本嘛謝謝

**Comment by jayeew** [comment]
这个错误具体在哪里出现的？还有别的错误提示么？我单看这个错误信息有点摸不到头脑欸。
tensorflow是1.13.1
keras是2.2.4

**Comment by Penny8336** [comment]
謝謝你的回覆,我使用了你的版本,正在訓練了!:)

**Comment by jayeew** [comment]
> 謝謝你的回覆,我使用了你的版本,正在訓練了!:)

嗯 这个issue我过段时间再关，有问题我们可以在这里交流
