### ISSUE TITLE
预测序列全部都是PAD

### ISSUE THREAD

**Issue by 1535966643** [jiayiwang5/Chinese-ChatBot#5]
你好，我参考您的代码实现了一遍，但是我预测不管是哪句话，结果都是PAD，请问怎么解决

**Comment by jayeew** [comment]
> 你好，我参考您的代码实现了一遍，但是我预测不管是哪句话，结果都是PAD，请问怎么解决
你可以直接运行我的模型吗？不确定你的问题出在哪里，但我的网络结构因该是没有问题。我之前遇到过预测都是同一句话的问题（但不是PAD），后来发现是预料预处理编码时误差了一位，进而导致整个模型不能正常工作。所以，我建议你详细检查一下编码，比如EOS，BOS插入是否正确，encoder，decoder输入编码是否统一，编码有没有出现位移等。

**Comment by 1535966643** [comment]
> > 你好，我参考您的代码实现了一遍，但是我预测不管是哪句话，结果都是PAD，请问怎么解决
> > 你可以直接运行我的模型吗？不确定你的问题出在哪里，但我的因此，我之前遇到过预测都是同一句话的问题（但不是PAD），后来发现是预料预编码编码时误差了一位，且导致整个模型无法正常工作。所以，我建议你详细检查一下编码，是否EOS，BOS插入正确正确，编码器，解码器输入编码是否统一，编码有没有出现位移等。

好的，谢谢你。我先按照你的建议来检查一遍。抱歉我没有直接跑你的模型，但是里面的有很多参考，方便把您的qq联系方式给我吗，想请教您

**Comment by jayeew** [comment]
> > > 你好，我参考您的代码实现了一遍，但是我预测不管是哪句话，结果都是PAD，请问怎么解决
> > > 你可以直接运行我的模型吗？不确定你的问题出在哪里，但我的因此，我之前遇到过预测都是同一句话的问题（但不是PAD），后来发现是预料预编码编码时误差了一位，且导致整个模型无法正常工作。所以，我建议你详细检查一下编码，是否EOS，BOS插入正确正确，编码器，解码器输入编码是否统一，编码有没有出现位移等。
> 
> 好的，谢谢你。我先按照你的建议来检查一遍。抱歉我没有直接跑你的模型，但是里面的有很多参考，方便把您的qq联系方式给我吗，想请教您

962326693
