### ISSUE TITLE
我是小白  这个下载下来可以直接用吗

### ISSUE THREAD

**Issue by 1761630764** [jiayiwang5/Chinese-ChatBot#6]

**Comment by jiayiwang5** [comment]
可以，但你至少得把import的包安装全了

**Comment by jayeew** [comment]
> _No description provided._

可以，但你至少得把import的包安装全了

**Comment by 1761630764** [comment]
运行环境吗 ？   难吗

**Comment by jayeew** [comment]
> 运行环境吗 ？ 难吗

缺什么会报什么错，报什么错你装什么就好

**Comment by 1761630764** [comment]
我电脑上只有python3.8   其他的不知道是啥

**Comment by 1761630764** [comment]
除了运行环境，还要下载啥东西

**Comment by 1761630764** [comment]
要是能出个视频教程就好了，嘿嘿

**Comment by jayeew** [comment]
> 除了运行环境，还要下载啥东西

tensorflow这个按照我的版本装，然后直接运行，之后报什么错就pip装什么

**Comment by jayeew** [comment]
> 要是能出个视频教程就好了，嘿嘿

纯小白的话先去学学keras和lstm，要不太费劲

**Comment by 1761630764** [comment]
我太难了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChiaEWg"<notifications@github.com&gt;; 
发送时间: 2020年4月12日(星期天) 晚上9:30
收件人: "jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;; 
抄送: "倾听者"<1761630764@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jiayiwang5/Chinese-ChatBot] 我是小白  这个下载下来可以直接用吗 (#6)





  
要是能出个视频教程就好了，嘿嘿
  
纯小白的话先去学学keras和lstm，要不太费劲

**Comment by jayeew** [comment]
> 我太难了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ChiaEWg"<notifications@github.com&gt;; 发送时间: 2020年4月12日(星期天) 晚上9:30 收件人: "jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;; 抄送: "倾听者"<1761630764@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [jiayiwang5/Chinese-ChatBot] 我是小白 这个下载下来可以直接用吗 (#6) 要是能出个视频教程就好了，嘿嘿 纯小白的话先去学学keras和lstm，要不太费劲 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

去coursera上看吴恩达的deep learning课就可以

**Comment by 1761630764** [comment]
这要学到什么程度才可以啊，python我还没学完




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ChiaEWg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月12日(星期天) 晚上9:34
收件人:&nbsp;"jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;;
抄送:&nbsp;"倾听者"<1761630764@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jiayiwang5/Chinese-ChatBot] 我是小白  这个下载下来可以直接用吗 (#6)





  
我太难了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ChiaEWg"<notifications@github.com&gt;; 发送时间: 2020年4月12日(星期天) 晚上9:30 收件人: "jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;; 抄送: "倾听者"<1761630764@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [jiayiwang5/Chinese-ChatBot] 我是小白 这个下载下来可以直接用吗 (#6) 要是能出个视频教程就好了，嘿嘿 纯小白的话先去学学keras和lstm，要不太费劲 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
去coursera上看吴恩达的deep learning课就可以

**Comment by jayeew** [comment]
> 这要学到什么程度才可以啊，python我还没学完
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ChiaEWg"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月12日(星期天) 晚上9:34 收件人:&nbsp;"jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;; 抄送:&nbsp;"倾听者"<1761630764@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [jiayiwang5/Chinese-ChatBot] 我是小白 这个下载下来可以直接用吗 (#6) 我太难了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ChiaEWg"<notifications@github.com&gt;; 发送时间: 2020年4月12日(星期天) 晚上9:30 收件人: "jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;; 抄送: "倾听者"<1761630764@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [jiayiwang5/Chinese-ChatBot] 我是小白 这个下载下来可以直接用吗 (#6) 要是能出个视频教程就好了，嘿嘿 纯小白的话先去学学keras和lstm，要不太费劲 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 去coursera上看吴恩达的deep learning课就可以 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

少则三四个星期，多了不好说，加油
