### ISSUE TITLE
请问下这个怎么运行

### ISSUE THREAD

**Issue by bushizhangwudia** [jiayiwang5/Chinese-ChatBot#7]
可以指导下怎么运行吗

**Comment by jayeew** [comment]
readme里不是写了咋运行吗？哭唧唧

---原始邮件---
发件人: "张无敌"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 上午9:04
收件人: "jiayiwang5/Chinese-ChatBot"<Chinese-ChatBot@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [jiayiwang5/Chinese-ChatBot] 请问下这个怎么运行 (#7)




 
可以指导下怎么运行吗

**Comment by bushizhangwudia** [comment]
python chatbot_inference_Attention.ipynb
显示
Traceback (most recent call last):
  File "chatbot_inference_Attention.ipynb", line 372, in <module>
    "scrolled": true
NameError: name 'true' is not defined

**Comment by jayeew** [comment]
> python chatbot_inference_Attention.ipynb
> 显示
> Traceback (most recent call last):
>   File "chatbot_inference_Attention.ipynb", line 372, in <module>
>     "scrolled": true
> NameError: name 'true' is not defined
> 

不好意思 我在外面手头没电脑，回头我看看，此外你的tensorflow和keras版本和我一致么

**Comment by bushizhangwudia** [comment]
版本都是一样的，然后不行。因为是学习阶段，麻烦作者了。

**Comment by bushizhangwudia** [comment]
> > python chatbot_inference_Attention.ipynb
> > 显示
> > Traceback (most recent call last):
> > File "chatbot_inference_Attention.ipynb", line 372, in 
> > "scrolled": true
> > NameError: name 'true' is not defined
> 
> 不好意思 我在外面手头没电脑，回头我看看，此外你的tensorflow和keras版本和我一致么
