### ISSUE TITLE
误关了个issues

### ISSUE THREAD

**Issue by bushizhangwudia** [jiayiwang5/Chinese-ChatBot#8]
我的版本和你的一样然后运行
python chatbot_inference_Attention.ipynb
显示
Traceback (most recent call last):
File "chatbot_inference_Attention.ipynb", line 372, in 
"scrolled": true
NameError: name 'true' is not defined

**Comment by jayeew** [comment]
> 我的版本和你的一样然后运行
> python chatbot_inference_Attention.ipynb
> 显示
> Traceback (most recent call last):
> File "chatbot_inference_Attention.ipynb", line 372, in
> "scrolled": true
> NameError: name 'true' is not defined

这个报错的地方具体在哪里啊，我用jupyter显示不了372行，scrolled貌似是个参数？我也没找到啊。

**Comment by jayeew** [comment]
> 我的版本和你的一样然后运行
> python chatbot_inference_Attention.ipynb
> 显示
> Traceback (most recent call last):
> File "chatbot_inference_Attention.ipynb", line 372, in
> "scrolled": true
> NameError: name 'true' is not defined

我谷歌搜了一下，这是jupyter下导入numpy时产生的一个错误，这是问题链接[点我，好哥哥](https://stackoverflow.com/questions/56427716/unable-to-import-numpy-in-jupyter-instead-getting-nameerror-true-is-not-def)，题主看起来是解决了，你可以试试。
