### ISSUE TITLE
运行到加载.h5时发生了错误，我想知道该怎么解决

### ISSUE THREAD

**Issue by EchoSixHIYA** [jiayiwang5/Chinese-ChatBot#9]
错误信息
Traceback (most recent call last):
  File "E:/360MoveData/Users/Administrator/Desktop/CHAT2/chatbot_inference_Attention.py", line 119, in <module>
    model.load_weights('models/W--184-0.5949-.h5')
ValueError: Dimension 0 in both shapes must be equal, but are 3 and 43350. Shapes are [3,100] and [43350,100]. for 'Assign' (op: 'Assign') with input shapes: [3,100], [43350,100].

**Comment by jayeew** [comment]
> 错误信息
> Traceback (most recent call last):
> File "E:/360MoveData/Users/Administrator/Desktop/CHAT2/chatbot_inference_Attention.py", line 119, in
> model.load_weights('models/W--184-0.5949-.h5')
> ValueError: Dimension 0 in both shapes must be equal, but are 3 and 43350. Shapes are [3,100] and [43350,100]. for 'Assign' (op: 'Assign') with input shapes: [3,100], [43350,100].

你改了哪的数据格式吧，训练好的模型里分词结果是43350个，经过embedding降为到100，而你的第一个维度只有3

**Comment by EchoSixHIYA** [comment]
谢谢
这之后我重新下载了代码，运行getdata之后再次尝试运行chatbot_inference_Attention
但是这次显示vocab_size为43360，还是无法加载已训练好的h5文件，如果手动将第一个维度设为43350强行加载，预测answer时会报43358不在范围内
错误信息
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 43358 is not in [0, 43350)

**Comment by EchoSixHIYA** [comment]
> > 错误信息
> > Traceback (most recent call last):
> > File "E:/360MoveData/Users/Administrator/Desktop/CHAT2/chatbot_inference_Attention.py", line 119, in
> > model.load_weights('models/W--184-0.5949-.h5')
> > ValueError: Dimension 0 in both shapes must be equal, but are 3 and 43350. Shapes are [3,100] and [43350,100]. for 'Assign' (op: 'Assign') with input shapes: [3,100], [43350,100].
> 
> 你改了哪的数据格式吧，训练好的模型里分词结果是43350个，经过embedding降为到100，而你的第一个维度只有3

谢谢
这之后我重新下载了代码，运行getdata之后再次尝试运行chatbot_inference_Attention
但是这次显示vocab_size为43360，还是无法加载已训练好的h5文件，如果手动将第一个维度设为43350强行加载，预测answer时会报43358不在范围内
错误信息
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 43358 is not in [0, 43350)

**Comment by jayeew** [comment]
> > > 错误信息
> > > Traceback (most recent call last):
> > > File "E:/360MoveData/Users/Administrator/Desktop/CHAT2/chatbot_inference_Attention.py", line 119, in
> > > model.load_weights('models/W--184-0.5949-.h5')
> > > ValueError: Dimension 0 in both shapes must be equal, but are 3 and 43350. Shapes are [3,100] and [43350,100]. for 'Assign' (op: 'Assign') with input shapes: [3,100], [43350,100].
> > 
> > 
> > 你改了哪的数据格式吧，训练好的模型里分词结果是43350个，经过embedding降为到100，而你的第一个维度只有3
> 
> 谢谢
> 这之后我重新下载了代码，运行getdata之后再次尝试运行chatbot_inference_Attention
> 但是这次显示vocab_size为43360，还是无法加载已训练好的h5文件，如果手动将第一个维度设为43350强行加载，预测answer时会报43358不在范围内
> 错误信息
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 43358 is not in [0, 43350)

你应该发现问题所在了，我训练模型的时候词袋里共有43350个词，所以模型就是按这个保存的。你运行getdata之后是43360，多出了10个词（不知道为什么，可能你的分词结果和我的分词结果不太一样？），不仅仅是词数目对不上而已，词的编号大概率也对不上。
所以你要么重新训练用你自己的模型；要么重新下载代码直接跑chatbot_inference_Attention.py，别再跑getdata，因为新生成的语料文件会覆盖我之前保存的。

**Comment by EchoSixHIYA** [comment]
> > > > 错误信息
> > > > Traceback (most recent call last):
> > > > File "E:/360MoveData/Users/Administrator/Desktop/CHAT2/chatbot_inference_Attention.py", line 119, in
> > > > model.load_weights('models/W--184-0.5949-.h5')
> > > > ValueError: Dimension 0 in both shapes must be equal, but are 3 and 43350. Shapes are [3,100] and [43350,100]. for 'Assign' (op: 'Assign') with input shapes: [3,100], [43350,100].
> > > 
> > > 
> > > 你改了哪的数据格式吧，训练好的模型里分词结果是43350个，经过embedding降为到100，而你的第一个维度只有3
> > 
> > 
> > 谢谢
> > 这之后我重新下载了代码，运行getdata之后再次尝试运行chatbot_inference_Attention
> > 但是这次显示vocab_size为43360，还是无法加载已训练好的h5文件，如果手动将第一个维度设为43350强行加载，预测answer时会报43358不在范围内
> > 错误信息
> > tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 43358 is not in [0, 43350)
> 
> 你应该发现问题所在了，我训练模型的时候词袋里共有43350个词，所以模型就是按这个保存的。你运行getdata之后是43360，多出了10个词（不知道为什么，可能你的分词结果和我的分词结果不太一样？），不仅仅是词数目对不上而已，词的编号大概率也对不上。
> 所以你要么重新训练用你自己的模型；要么重新下载代码直接跑chatbot_inference_Attention.py，别再跑getdata，因为新生成的语料文件会覆盖我之前保存的。

谢谢了：）
